[default]
address = "127.0.0.1"
port = 8001
log_level = "normal"
cli_colors = true
secret_key = "EkYQbaqUZ3GzhHvA4t83v6qN1lAavG2rrySb0zl5tbs="

[default.limits]
form = "0 kB"
json = "1 MiB"
msgpack = "0 MiB"
"file/jpg" = "0 MiB"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5